COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//incubator/api:onos-incubator-api',
    '//lib:floodlightpof',
]

TEST_DEPS = [
    '//lib:TEST',
]

osgi_jar_with_tests (
    name = 'onos-core-serializers',
    deps = COMPILE_DEPS,
    test_deps = TEST_DEPS,
    visibility = ['PUBLIC'],
)
