APPS = [
    'org.onosproject.hostprovider',
    'org.onosproject.lldpprovider',
    'org.onosproject.pof-base',
]

onos_app (
    app_name = 'org.onosproject.pof',
    title = 'POF Meta App',
    category = 'Provider',
    url = 'http://onosproject.org',
    description = 'POF southbound meta application.',
    included_bundles = [ '//utils/osgi:onlab-osgi' ],  # FIXME to allow hollow oar files
    required_apps = APPS,
)
